### ISSUE TITLE
Banner Image on Landing pages

### ISSUE THREAD

**Issue by travula** [vlead/vlabs-landing-pages#103]
@priya100raman @BalammaBoya 

We need a high resolution banner image.  @BalammaBoya, please specify the dimensions and resolution.

**Comment by BalammaBoya** [comment]
Banner Dimensions are 2272X600px and Resolution: 500dpi

**Comment by priya100raman** [comment]
Let us change the banner . Why stick with what is current there...@Balamma
could you please get some options.

On 13 Oct 2017 4:41 pm, "BalammaBoya" <notifications@github.com> wrote:

Banner Dimensions are 2272X600px and Resolution: 500dpi

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vlead/vlabs-landing-pages/issues/103#issuecomment-336422730>,
or mute the thread

**Comment by BalammaBoya** [comment]
Here attached one banner image

![bg1](https://user-images.githubusercontent.com/22425444/31546559-71cdf86a-b041-11e7-8b0e-0c82de7ad268.jpg)

**Comment by BalammaBoya** [comment]
Attached new banner image

![banner_img](https://user-images.githubusercontent.com/22425444/31604732-d3dd9fb4-b281-11e7-9aa9-647193ed53c1.jpg)
