### ISSUE TITLE
SSAD: Unable to access source code of iframe due to cross origin error

### ISSUE THREAD

**Issue by SurendraTelidevara** [vlead/vlabs-landing-pages#50]
Motive: Tried to access source code of the source of the iframe to parse for some key words to know the status of login. Tried running the below code snippet.
 
"document.getElementById("iframe_id").contentWindow.document.body.innerHTML"
Error obtained: "SecurityError: Permission denied to access property "document" on cross-origin object"

We have also explored  other methods, but ended up with similar results.

**Comment by travula** [comment]
@SurendraTelidevara 

I was running `https://themeless.vlabs.ac.in` in the sandboxed frame.  

I ran the following commands from the javascript console
`var iframe = document.getElementById("iframe1");`
 returns an iframe element.

'var content = iframe.contentWindow.document;`
returns an exception
```
VM163:1 Uncaught DOMException: Blocked a frame with origin "http://localhost:8000" from accessing a cross-origin frame.
    at <anonymous>:1:35
```

What this means is that a script served by localhost is trying to access the content of an iframe served from another server.   This is a no go.  Refer [stackoverflow](https://stackoverflow.com/questions/6170925/get-dom-content-of-cross-domain-iframe).

The same stackoverflow issue suggests a solution. 

```
CORS headers: just add the following header to the iframed website:
Access-Control-Allow-Origin: http://foo.example

where http://foo.example is the domain hosting the page with the iframe in it
```

To implement the above solution. you will have to set the `Access-Control-Allow-Origin` to `*` and access the content.  Since you do have access to the machine `https://themeless.vlabs.ac.in`,  you will have to do the following:
1. set up an Open edX machine in your dev environment.  Please follow the [document](https://github.com/vlead/vlead-onboarding/blob/master/src/set-up-vlead-openedx-vagrant-box.org) to do so.
2.  You will also have to set `x_frame_option` to `allow`.  Follow the [instuctions](https://github.com/vlead/vlead-onboarding/blob/master/src/set-up-vlead-openedx-vagrant-box.org#enable-x_frame_option-in-ed-platform) to set it.
3.  you will have to figure out how to set `Access-Control-Allow-Origin` to `*` for the same server.

**Comment by travula** [comment]
To implement the other solution using [postMessages](https://stackoverflow.com/questions/9393532/cross-domain-iframe-issue/9393545#9393545), you could do the following:

1.  Find out where the login and register pages are in Open edX
2. Write java script code into these pages such that different messages could be posted to the top level on different events like, onload, on submission, on successful login, on successful registration etc.

**Comment by travula** [comment]
@sivashankerN

**Comment by travula** [comment]
The earlier error posted is on chrome.

This is the same error where the explanation is not given.  On my firefox browser I get
```
SecurityError: Permission denied to access property "document" on cross-origin object
```

**Comment by travula** [comment]
This is resolved by using [postMessages](https://stackoverflow.com/questions/9393532/cross-domain-iframe-issue/9393545#9393545)

**Comment by travula** [comment]
cannot set document.domain in sandboxed iframe

https://www.fxsitecompat.com/en-CA/docs/2013/setting-document-domain-in-a-sandboxed-iframe-is-no-longer-allowed/

**Comment by travula** [comment]
cross window communication

https://javascript.info/cross-window-communication
