### ISSUE TITLE
Verifying the list of captured labs 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#91]
Verifying the count of captured labs of lds data base with lab-specs.

**Comment by mrudhvika940** [comment]
As `System Analysis and Design virtual Lab` is listed in lab-to-id-mapping but it was not present in any web pages(vlabs.ac.in and vlans.co.in). The final count we got is 177.

**Comment by sanchita-dixit** [comment]
The list of labs have been verified from [vlabs landing page](https://vlabs.ac.in) and [list of labs](https://github.com/vlead/lab-specifications/blob/master/lab-to-id-mapping.org) and the final count has been tallied to 177. Since there are no more labs which needs to added to the LDS database and we have captured the data of all the labs, this issue can be closed.
